### ISSUE TITLE
DMG does not work on OSX 10.11.6 on MacBook Pro

### ISSUE THREAD

**Issue by CraigShields** [eivindveg/HotSUploader#134]
Hello,
I installed the latest version of the uploader but when I open it it just crashes with the application not even appearing on screen. Tried the same with previous versions, no luck. I'm running OSX 10.11.6 on a Mid-2015 MacBook Pro.

**Comment by zhedar** [comment]
Could you try running the jar file from the terminal via `java -jar path/to/HotS.Replay.Uploader-2.1.1.jar` and post the output so that we could diagnose the crash?

@eivindveg Do we have a file log already or did we forget about that?

**Comment by CraigShields** [comment]
I just tried that and the terminal returns:

"Error: Unable to access jarfile users/craig/downloads/HotS.Replay.Uploader-2.1.1.jar"

Did I do something wrong? I'm not very practical with the Terminal.

**Comment by zhedar** [comment]
What does the command `java -version` say? You may not have installed the correct JDK to execute the jar file directly. Otherwise it should be bundled into the DMG file, so that won't be an issue normally.

Anyway, you may not even be able to use the jar file directly, as I just got an error trying to do so.

@eivindveg Does that work for you? All I'm getting is:
`org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [ninja.eivind.hotsreplayuploader.Client]; nested exception is java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.` Seems like we're missing a configuration there.

**Comment by CraigShields** [comment]
@zhedar 

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by zhedar** [comment]
Just tried it myself and in this case the error message seems to be, that your path is incorrect. Normally you should just be able to do:

    cd #change to default dir
    cd Downloads
    java -jar HotS.Replay.aploader-2.1.1.jar

or simply `java -jar Downloads/HotS.Replay.aploader-2.1.1.jar` from a fresh terminal.

**Comment by CraigShields** [comment]
Got it.

Here is the log:




  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.1.1)

2016-10-03 18:08:38.372  INFO 1121 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Starting application on Michaels-MBP-2 with PID 1121 (started by Michael in /Users/Michael)
2016-10-03 18:08:38.373  INFO 1121 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
2016-10-03 18:08:38.414  INFO 1121 --- [JavaFX-Launcher] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@4167086d: startup date [Mon Oct 03 18:08:38 CEST 2016]; root of context hierarchy
2016-10-03 18:08:38.567  WARN 1121 --- [JavaFX-Launcher] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [ninja.eivind.hotsreplayuploader.Client]; nested exception is java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
2016-10-03 18:08:38.576 ERROR 1121 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [ninja.eivind.hotsreplayuploader.Client]; nested exception is java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:489) ~[HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:191) ~[HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:321) ~[HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243) ~[HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) ~[HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98) ~[HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681) ~[HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523) ~[HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369) ~[HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) ~[HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at ninja.eivind.hotsreplayuploader.Client.init(Client.java:89) [HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:841) [jfxrt.jar:na]
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182) [jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
	at org.springframework.util.Assert.notEmpty(Assert.java:276) ~[HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at org.springframework.boot.autoconfigure.EnableAutoConfigurationImportSelector.getCandidateConfigurations(EnableAutoConfigurationImportSelector.java:145) ~[HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at org.springframework.boot.autoconfigure.EnableAutoConfigurationImportSelector.selectImports(EnableAutoConfigurationImportSelector.java:84) ~[HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:481) ~[HotS.Replay.Uploader-2.1.1.jar:2.1.1]
	... 15 common frames omitted

Exception in Application init method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application init method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:912)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [ninja.eivind.hotsreplayuploader.Client]; nested exception is java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:489)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:191)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:321)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at ninja.eivind.hotsreplayuploader.Client.init(Client.java:89)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:841)
	... 2 more
Caused by: java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
	at org.springframework.util.Assert.notEmpty(Assert.java:276)
	at org.springframework.boot.autoconfigure.EnableAutoConfigurationImportSelector.getCandidateConfigurations(EnableAutoConfigurationImportSelector.java:145)
	at org.springframework.boot.autoconfigure.EnableAutoConfigurationImportSelector.selectImports(EnableAutoConfigurationImportSelector.java:84)
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:481)
	... 15 more
Exception running application ninja.eivind.hotsreplayuploader.Client

**Comment by zhedar** [comment]
Sadly this is the log, that I got aswell, which seems to disguise the real error. We need to fix that first, be will get back to you then.

**Comment by zhedar** [comment]
OK, here's a fixed jar, maybe you can use this one to try again and get the real error:
[HotS Replay Uploader.jar.zip](https://github.com/eivindveg/HotSUploader/files/506696/HotS.Replay.Uploader.jar.zip)

**Comment by eivindveg** [comment]
Oh.. Sadly, I seem to have forgotten to deal with the Spring Boot class loader.

**Comment by zhedar** [comment]
I just threw 

    <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
    </plugin>

and 
`<start-class>ninja.eivind.hotsreplayuploader.Client</start-class>` in the pom to make it work with `mvn package clean` to produce the test jar. Also threw out a jar plugin, therefore not sure about the implications. Can't check right know, as I'm about to be called and get out of the house any minute ;)

**Comment by eivindveg** [comment]
Essentially we need to do some lib repackaging/scrapping, using Boot's main class and our Boot manifest in order to be compatible with both javafx and boot plugins.

**Comment by eivindveg** [comment]
Jar files now work as intended. Could you please perform a test using that jar file again to determine the cause of your crash?

**Comment by bdigregorio** [comment]
Seems to be something related to fonts. 

```
14:36:44.620 [main] INFO ninja.eivind.hotsreplayuploader.services.platform.PlatformServiceFactoryBean - Constructing PlatformService for Mac OS X
14:36:44.628 [main] INFO ninja.eivind.hotsreplayuploader.Client - Launching without preloader.

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.0.RELEASE)

2016-12-16 14:36:45.609  INFO 21312 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Starting application on MTVL13b8bd53c.local with PID 21312 (/Users/bdigregorio/Downloads/HotS Replay Uploader.jar started by bdigregorio in /Users/bdigregorio/Downloads)
2016-12-16 14:36:45.611  INFO 21312 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
2016-12-16 14:36:45.675  INFO 21312 --- [JavaFX-Launcher] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@35d169a1: startup date [Fri Dec 16 14:36:45 PST 2016]; root of context hierarchy
2016-12-16 14:36:46.049  INFO 21312 --- [JavaFX-Launcher] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'statusBinder' with a different definition: replacing [Generic bean: class [ninja.eivind.hotsreplayuploader.models.stringconverters.StatusBinder]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in URL [jar:file:/Users/bdigregorio/Downloads/HotS%20Replay%20Uploader.jar!/BOOT-INF/classes!/ninja/eivind/hotsreplayuploader/models/stringconverters/StatusBinder.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=hotSReplayUploaderConfiguration; factoryMethodName=statusBinder; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [ninja/eivind/hotsreplayuploader/di/HotSReplayUploaderConfiguration.class]]
2016-12-16 14:36:46.237  INFO 21312 --- [JavaFX-Launcher] trationDelegate$BeanPostProcessorChecker : Bean 'hotslogs-s3credentials' of type [class ninja.eivind.hotsreplayuploader.providers.hotslogs.HotsLogsAWSCredentials] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2016-12-16 14:36:46.323  INFO 21312 --- [JavaFX-Launcher] n.e.h.d.HotSReplayUploaderConfiguration  : Building ObjectMapper
2016-12-16 14:36:46.427  INFO 21312 --- [JavaFX-Launcher] n.e.h.s.p.PlatformServiceFactoryBean     : Constructing PlatformService for Mac OS X
2016-12-16 14:36:46.497  INFO 21312 --- [JavaFX-Launcher] n.e.h.files.AccountDirectoryWatcher      : Initiating watch against directories:
2016-12-16 14:36:46.512  INFO 21312 --- [JavaFX-Launcher] n.e.h.files.AccountDirectoryWatcher      : Watcher initiated.
2016-12-16 14:36:47.035  INFO 21312 --- [JavaFX-Launcher] n.e.h.r.DataSourceFactoryBean            : Setting up DataSource with URL jdbc:h2:/Users/bdigregorio/Library/Application Support/HotSReplayUploader/database
2016-12-16 14:36:47.045  INFO 21312 --- [JavaFX-Launcher] o.f.core.internal.util.VersionPrinter    : Flyway 4.0.3 by Boxfuse
2016-12-16 14:36:47.258  INFO 21312 --- [JavaFX-Launcher] o.f.c.i.dbsupport.DbSupportFactory       : Database: jdbc:h2:/Users/bdigregorio/Library/Application Support/HotSReplayUploader/database (H2 1.4)
2016-12-16 14:36:47.339  INFO 21312 --- [JavaFX-Launcher] o.f.core.internal.command.DbMigrate      : Current version of schema "PUBLIC": 2.0
2016-12-16 14:36:47.340  INFO 21312 --- [JavaFX-Launcher] o.f.core.internal.command.DbMigrate      : Schema "PUBLIC" is up to date. No migration necessary.
2016-12-16 14:36:47.399  INFO 21312 --- [JavaFX-Launcher] n.e.h.r.DataSourceFactoryBean            : Setting up DataSource with URL jdbc:h2:/Users/bdigregorio/Library/Application Support/HotSReplayUploader/database
2016-12-16 14:36:47.406  INFO 21312 --- [JavaFX-Launcher] o.f.c.i.dbsupport.DbSupportFactory       : Database: jdbc:h2:/Users/bdigregorio/Library/Application Support/HotSReplayUploader/database (H2 1.4)
2016-12-16 14:36:47.421  INFO 21312 --- [JavaFX-Launcher] o.f.core.internal.command.DbMigrate      : Current version of schema "PUBLIC": 2.0
2016-12-16 14:36:47.421  INFO 21312 --- [JavaFX-Launcher] o.f.core.internal.command.DbMigrate      : Schema "PUBLIC" is up to date. No migration necessary.
2016-12-16 14:36:47.569  INFO 21312 --- [JavaFX-Launcher] n.e.h.services.HeroService               : Instantiating HeroService
2016-12-16 14:36:47.570  INFO 21312 --- [JavaFX-Launcher] n.e.h.services.HeroService               : Instantiated HeroService
2016-12-16 14:36:47.577  INFO 21312 --- [JavaFX-Launcher] n.e.h.services.UploaderService           : Instantiating UploaderService
2016-12-16 14:36:47.578  INFO 21312 --- [JavaFX-Launcher] n.e.h.services.UploaderService           : Instantiated UploaderService
2016-12-16 14:36:47.588  INFO 21312 --- [JavaFX-Launcher] n.e.h.services.UploaderService           : Initializing UploaderService
2016-12-16 14:36:47.589  INFO 21312 --- [JavaFX-Launcher] n.e.h.files.AccountDirectoryWatcher      : Adding listener class ninja.eivind.hotsreplayuploader.services.UploaderService$$Lambda$102/1832288319
2016-12-16 14:36:47.589  INFO 21312 --- [JavaFX-Launcher] n.e.h.services.UploaderService           : Registering initial replays.
2016-12-16 14:36:47.828  INFO 21312 --- [JavaFX-Launcher] n.e.h.services.UploaderService           : Updating counter for uploaded replays.
2016-12-16 14:36:47.830  INFO 21312 --- [JavaFX-Launcher] n.e.h.services.UploaderService           : Registering not yet uploaded replays.
2016-12-16 14:36:47.831  INFO 21312 --- [JavaFX-Launcher] n.e.h.services.UploaderService           : Initialized UploaderService
2016-12-16 14:36:47.934  INFO 21312 --- [JavaFX-Launcher] o.f.c.i.dbsupport.DbSupportFactory       : Database: jdbc:h2:/Users/bdigregorio/Library/Application Support/HotSReplayUploader/database (H2 1.4)
2016-12-16 14:36:47.945  INFO 21312 --- [JavaFX-Launcher] o.f.core.internal.command.DbValidate     : Successfully validated 1 migration (execution time 00:00.003s)
2016-12-16 14:36:47.952  INFO 21312 --- [JavaFX-Launcher] o.f.core.internal.command.DbMigrate      : Current version of schema "PUBLIC": 2.0
2016-12-16 14:36:47.952  INFO 21312 --- [JavaFX-Launcher] o.f.core.internal.command.DbMigrate      : Schema "PUBLIC" is up to date. No migration necessary.
2016-12-16 14:36:48.034  INFO 21312 --- [JavaFX-Launcher] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-12-16 14:36:48.047  INFO 21312 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Started application in 2.91 seconds (JVM running for 3.904)
2016-12-16 14:36:48.482  INFO 21312 --- [lication Thread] n.e.h.files.AccountDirectoryWatcher      : Adding listener class ninja.eivind.hotsreplayuploader.window.HomeController$$Lambda$140/2076178469
2016-12-16 14:36:48.487  INFO 21312 --- [      Thread-21] n.e.h.f.t.RecursiveTempWatcher           : Starting watch for Caches in /Users/bdigregorio/Library
2016-12-16 14:36:48.487  INFO 21312 --- [      Thread-22] n.e.h.f.t.RecursiveTempWatcher           : Starting watch for TemporaryItems in /Users/bdigregorio/Library/Caches
2016-12-16 14:36:48.555  INFO 21312 --- [lication Thread] n.e.h.d.nodes.SpringAwareBuilderFactory  : Creating custom component ninja.eivind.hotsreplayuploader.window.nodes.HotsLogsNode
2016-12-16 14:36:48.707  INFO 21312 --- [      Thread-26] n.e.h.utils.SimpleHttpClient             : Opening connection to https://www.hotslogs.com/API/Data/Heroes
2016-12-16 14:36:48.714  INFO 21312 --- [      Thread-25] n.e.h.utils.SimpleHttpClient             : Opening connection to https://www.hotslogs.com/API/Players/1/1/407349
2016-12-16 14:36:48.725  INFO 21312 --- [lication Thread] n.e.h.d.nodes.SpringAwareBuilderFactory  : Creating custom component ninja.eivind.hotsreplayuploader.window.nodes.UploaderNode
2016-12-16 14:36:48.767  INFO 21312 --- [lication Thread] n.e.h.window.nodes.UploaderNode          : Initializing UploaderNode
2016-12-16 14:36:48.769  INFO 21312 --- [lication Thread] n.e.h.services.UploaderService           : Attempting to take file from queue
2016-12-16 14:36:48.771  INFO 21312 --- [lication Thread] n.e.h.services.UploaderService           : Prepared task
2016-12-16 14:36:48.771  INFO 21312 --- [pool-3-thread-1] n.e.h.concurrent.tasks.UploadTask        : Uploading replayFile Battlefield of Eternity (2).StormReplay
2016-12-16 14:36:48.798  INFO 21312 --- [lication Thread] n.e.h.window.nodes.UploaderNode          : UploaderNode initialized
2016-12-16 14:36:48.809  INFO 21312 --- [lication Thread] n.e.h.window.HomeController              : Initializing HomeController
2016-12-16 14:36:48.810  INFO 21312 --- [lication Thread] n.e.h.window.HomeController              : Initialized HomeController
2016-12-16 14:36:48.810  INFO 21312 --- [      Thread-27] n.e.h.utils.SimpleHttpClient             : Opening connection to https://api.github.com/repos/eivindveg/HotSUploader/releases
2016-12-16 14:36:48.818  INFO 21312 --- [pool-3-thread-1] n.e.h.p.hotslogs.HotsLogsProvider        : Calculated matchId to bee2f24bf6-8758-647d-2e09-cf4a068b2c6b
2016-12-16 14:36:48.818  INFO 21312 --- [pool-3-thread-1] n.e.h.utils.SimpleHttpClient             : Opening connection to https://www.hotslogs.com/UploadFile?Source=HotSLogsUploaderFX&ReplayHash=e2f24bf6-8758-647d-2e09-cf4a068b2c6b
2016-12-16 14:36:49.270 ERROR 21312 --- [lication Thread] ninja.eivind.hotsreplayuploader.Client   : Failed to start

java.lang.NullPointerException: null
	at com.sun.javafx.font.MacFontFinder.populateFontFileNameMap(MacFontFinder.java:99) ~[jfxrt.jar:na]
	at com.sun.javafx.font.PrismFontFactory.getFullNameToFileMap(PrismFontFactory.java:1740) ~[jfxrt.jar:na]
	at com.sun.javafx.font.PrismFontFactory.getFontResource(PrismFontFactory.java:469) ~[jfxrt.jar:na]
	at com.sun.javafx.font.LogicalFont.getSlot0Resource(LogicalFont.java:194) ~[jfxrt.jar:na]
	at com.sun.javafx.font.LogicalFont.getDefaultAAMode(LogicalFont.java:409) ~[jfxrt.jar:na]
	at com.sun.javafx.font.LogicalFont.getStrike(LogicalFont.java:413) ~[jfxrt.jar:na]
	at com.sun.javafx.font.PrismFont.getStrike(PrismFont.java:73) ~[jfxrt.jar:na]
	at com.sun.javafx.text.PrismTextLayout.setContent(PrismTextLayout.java:138) ~[jfxrt.jar:na]
	at javafx.scene.text.Text.getTextLayout(Text.java:229) ~[jfxrt.jar:na]
	at javafx.scene.text.Text.needsFullTextLayout(Text.java:184) ~[jfxrt.jar:na]
	at javafx.scene.text.Text.access$200(Text.java:95) ~[jfxrt.jar:na]
	at javafx.scene.text.Text$5.invalidated(Text.java:501) ~[jfxrt.jar:na]
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:111) ~[jfxrt.jar:na]
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146) ~[jfxrt.jar:na]
	at javafx.css.StyleableObjectProperty.set(StyleableObjectProperty.java:82) ~[jfxrt.jar:na]
	at javafx.scene.text.Text.setFont(Text.java:474) ~[jfxrt.jar:na]
	at com.sun.javafx.scene.control.skin.LabeledText.<init>(LabeledText.java:72) ~[jfxrt.jar:na]
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.<init>(LabeledSkinBase.java:125) ~[jfxrt.jar:na]
	at com.sun.javafx.scene.control.skin.LabelSkin.<init>(LabelSkin.java:39) ~[jfxrt.jar:na]
	at javafx.scene.control.Label.createDefaultSkin(Label.java:158) ~[jfxrt.jar:na]
	at javafx.scene.control.Control.impl_processCSS(Control.java:859) ~[jfxrt.jar:na]
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280) ~[jfxrt.jar:na]
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280) ~[jfxrt.jar:na]
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280) ~[jfxrt.jar:na]
	at javafx.scene.Node.processCSS(Node.java:9056) ~[jfxrt.jar:na]
	at javafx.scene.Scene.doCSSPass(Scene.java:545) ~[jfxrt.jar:na]
	at javafx.scene.Scene.preferredSize(Scene.java:1643) ~[jfxrt.jar:na]
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720) ~[jfxrt.jar:na]
	at javafx.stage.Window$9.invalidated(Window.java:846) ~[jfxrt.jar:na]
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109) ~[jfxrt.jar:na]
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144) ~[jfxrt.jar:na]
	at javafx.stage.Window.setShowing(Window.java:922) ~[jfxrt.jar:na]
	at javafx.stage.Window.show(Window.java:937) ~[jfxrt.jar:na]
	at javafx.stage.Stage.show(Stage.java:259) ~[jfxrt.jar:na]
	at ninja.eivind.hotsreplayuploader.Client.start(Client.java:116) ~[classes!/:2.1.1]
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863) [jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326) ~[jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_77]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]

Exception in Application start method
2016-12-16 14:36:49.308  INFO 21312 --- [lication Thread] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@35d169a1: startup date [Fri Dec 16 14:36:45 PST 2016]; root of context hierarchy
2016-12-16 14:36:49.310  INFO 21312 --- [lication Thread] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2016-12-16 14:36:49.310  INFO 21312 --- [lication Thread] n.e.h.files.AccountDirectoryWatcher      : Shutting down watch handlers
2016-12-16 14:36:49.311  INFO 21312 --- [pool-2-thread-1] n.e.h.files.WatchHandler                 : WatchHandler-/Users/bdigregorio/Library/Application Support/Blizzard/Heroes of the Storm/Accounts/328398658/1-Hero-1-5806050/Replays/Multiplayer was interrupted. Winding down thread.
2016-12-16 14:36:49.311  INFO 21312 --- [pool-2-thread-3] n.e.h.files.WatchHandler                 : WatchHandler-/Users/bdigregorio/Library/Application Support/Blizzard/Heroes of the Storm/Accounts/351231513/1-Hero-1-6852848/Replays/Multiplayer was interrupted. Winding down thread.
2016-12-16 14:36:49.311  INFO 21312 --- [pool-2-thread-4] n.e.h.files.WatchHandler                 : WatchHandler-/Users/bdigregorio/Library/Application Support/Blizzard/Heroes of the Storm/Accounts/126843/1-Hero-1-407349/Replays/Multiplayer was interrupted. Winding down thread.
2016-12-16 14:36:49.311  INFO 21312 --- [pool-2-thread-5] n.e.h.files.WatchHandler                 : WatchHandler-/Users/bdigregorio/Library/Application Support/Blizzard/Heroes of the Storm/Accounts/87213868/1-Hero-1-6834078/Replays/Multiplayer was interrupted. Winding down thread.
2016-12-16 14:36:49.311  INFO 21312 --- [pool-2-thread-2] n.e.h.files.WatchHandler                 : WatchHandler-/Users/bdigregorio/Library/Application Support/Blizzard/Heroes of the Storm/Accounts/146334/1-Hero-1-5818961/Replays/Multiplayer was interrupted. Winding down thread.
```

**Comment by eivindveg** [comment]
Yeah. Just verified that we never use any non-system fonts. On that note, [say hello to my little friend](https://bugs.openjdk.java.net/browse/JDK-8129405), a JDK bug. Right now, there doesn't seem to be anything we can do about it outright. Might work to actually include the needed font and only use that.

```
at com.sun.javafx.font.MacFontFinder.populateFontFileNameMap(MacFontFinder.java:99) ~[jfxrt.jar:na]
````
Could you decompile and look at the offending code, @zhedar?
