### ISSUE TITLE
Cannot Run jar with openjdk 11

### ISSUE THREAD

**Issue by fadeltd** [eivindveg/HotSUploader#168]
Hi, I'm trying to execute the .jar file on my Mac but it fails.

```
$ java -jar HotS.Replay.Uploader-2.1.5.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:89)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:89)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 15 more

```

I'm using the newest Open JDK 11

```
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

**Comment by iay** [comment]
This application uses JavaFX, which is no longer bundled with Java 11 (more information, e.g., [here](https://www.infoworld.com/article/3305073/java/removed-from-jdk-11-javafx-11-arrives-as-a-standalone-module.html)).

Assuming that this project is no longer maintained (no commits for more than a year, so I'm guessing no-one is working on it) you have a couple of options:
* [Download JavaFX](https://openjfx.io), and add it to the classpath when you invoke the application
* Install Java 8 as well as Java 11, and run the application under Java 8.

Hope that's of some use. I'm not the author, and I don't play HotS myself any more, so I can't really help other than pointing you in the right direction.
